### ISSUE TITLE
Add regex matchers

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/deployment-director#1]
We would like to be able to match against branches/tags using a regex:

```
when:
  branch: /v(\d+\.?)+/    # matches vX.Y.Z....
```

Note that we are not thinking to provide a differentiated "tag" matcher, because the lowest common denominator in CI tools is that branch and tag information are exchangeable. (i.e. Codeship just provides a `CI_BRANCH` env variable)

additionally, in the value maps, we should provide a way of using some generic identifier that is associated to the regex having matched , so if we have:

```
when:
  branch:
    - development
    - match: /release-.*/
      as: release-TAG
```

we can do:
```
then:
...
   parameters:
     target_server:
       key: branch
       map:
         development: staging_server
         release-TAG: release_server
```
